In [1]:
#Load Libraries and Business Dataset

import pandas as pd
import altair as alt

alt.data_transformers.disable_max_rows()

df = pd.read_csv("iowa_retail_business_registrations_sample.csv")

df.head()

,Active or Inactive Business,Tax Type,Retail Permit Number,Consolidated Number,Name of Business,Address of the Business,State,County Name,Registration County Number,Business Location County Number,Department City Code,City Location of Business,Business Zip Code,NAICS code,Description of type of NAICS code,Date Permit was Issued,Date Permit was Cancelled
0,Inactive,Retail Sales,100003115,NaN,DATAWORKS DEVELOPMENT INC,6608 216TH ST SW STE 100,WA,NaN,0.0,0,NaN,MOUNTLAKE TER,98043-2084,5112.0,Software Publishers,2019-03-07T00:00:00.000,2021-01-31T00:00:00.000
1,Active,Retail Sales,308700211,308700111,"NOURISH MIND & BODY, LLC",1366 275TH ST,IA,Buchanan,10.0,10,2.0,JESUP,50648-9457,621399.0,Offices of All Other Miscellaneous Health Prac...,2023-05-01T00:00:00.000,NaN
2,Inactive,Retail Sales,S00235563,S00235563,DROPZONE LLC,361 SOUTHWEST DR 307,AR,NaN,0.0,0,NaN,JONESBORO,72401-0000,441227.0,"Motorcycle, ATV, and All Other Motor Vehicle D...",2021-08-31T00:00:00.000,2022-07-31T00:00:00.000
3,Inactive,Retail Sales,177133565,NaN,"SIMMONS, RICHARD; TWO KAYAK WOODWORKING",509 SW ASH DR,IA,Polk,77.0,77,5.0,ANKENY,50023-2905,3219.0,Other Wood Product Manufacturing,2021-07-01T00:00:00.000,2024-06-01T00:00:00.000
4,Inactive,Retail Sales,633505392,NaN,NORTH FAYETTE COMMUNITY SCHOOL DIST,PO BOX 73 105 E MAIN ST,IA,Fayette,33.0,33,3.0,WEST UNION,52175-0073,7139.0,Other Amusement and Recreation Industries,2001-07-06T00:00:00.000,2021-11-11T00:00:00.000

In [2]:
#Prepare Business Data for Dashboard

df["Date Permit was Issued"] = pd.to_datetime(df["Date Permit was Issued"], errors="coerce")
df["Issue Year"] = df["Date Permit was Issued"].dt.year

df_dashboard = df.dropna(subset=[
    "Active or Inactive Business",
    "County Name",
    "Issue Year"
])

df_dashboard = df_dashboard[df_dashboard["Issue Year"] >= 2000]
df_dashboard = df_dashboard[df_dashboard["Issue Year"] <= 2025]

df_dashboard.head()

,Active or Inactive Business,Tax Type,Retail Permit Number,Consolidated Number,Name of Business,Address of the Business,State,County Name,Registration County Number,Business Location County Number,Department City Code,City Location of Business,Business Zip Code,NAICS code,Description of type of NAICS code,Date Permit was Issued,Date Permit was Cancelled,Issue Year
1,Active,Retail Sales,308700211,308700111,"NOURISH MIND & BODY, LLC",1366 275TH ST,IA,Buchanan,10.0,10,2.0,JESUP,50648-9457,621399.0,Offices of All Other Miscellaneous Health Prac...,2023-05-01,NaN,2023
3,Inactive,Retail Sales,177133565,NaN,"SIMMONS, RICHARD; TWO KAYAK WOODWORKING",509 SW ASH DR,IA,Polk,77.0,77,5.0,ANKENY,50023-2905,3219.0,Other Wood Product Manufacturing,2021-07-01,2024-06-01T00:00:00.000,2021
4,Inactive,Retail Sales,633505392,NaN,NORTH FAYETTE COMMUNITY SCHOOL DIST,PO BOX 73 105 E MAIN ST,IA,Fayette,33.0,33,3.0,WEST UNION,52175-0073,7139.0,Other Amusement and Recreation Industries,2001-07-06,2021-11-11T00:00:00.000,2001
7,Inactive,Retail Sales,168003811,NaN,"CHANCE, LINDA K; LINDAS QUILTING",1264 625TH AVE,IA,Monroe,68.0,68,3.0,LOVILIA,50150-8756,NaN,NaN,2008-07-01,2020-06-30T00:00:00.000,2008
9,Active,Retail Sales,306903525,306903525,"OLSON, MARK A",1239 JAVELIN PL,IA,Boone,8.0,8,3.0,OGDEN,50212-7425,457110.0,Gasoline Stations with Convenience Stores,2025-05-16,NaN,2025

In [3]:
selection = alt.selection_point(fields=["Active or Inactive Business"])

chart1 = alt.Chart(df_dashboard).mark_bar().encode(
    x=alt.X("Active or Inactive Business:N", title="Business Status"),
    y=alt.Y("count():Q", title="Number of Businesses"),
    color=alt.Color("Active or Inactive Business:N", title="Business Status"),
    opacity=alt.condition(selection, alt.value(1), alt.value(0.25)),
    tooltip=[
        alt.Tooltip("Active or Inactive Business:N", title="Business Status"),
        alt.Tooltip("count():Q", title="Number of Businesses")
    ]
).add_params(
    selection
).properties(
    title="Active vs Inactive Businesses",
    width=260,
    height=320
)

chart2 = alt.Chart(df_dashboard).mark_line(point=True).encode(
    x=alt.X("Issue Year:O", sort="ascending", title="Year"),
    y=alt.Y("count():Q", title="Number of Businesses"),
    color=alt.Color("Active or Inactive Business:N", title="Business Status"),
    tooltip=[
        alt.Tooltip("Issue Year:O", title="Year"),
        alt.Tooltip("Active or Inactive Business:N", title="Business Status"),
        alt.Tooltip("count():Q", title="Number of Businesses")
    ]
).transform_filter(
    selection
).properties(
    title="Business Registrations Over Time",
    width=650,
    height=320
)

dashboard = chart1 | chart2

dashboard

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.HConcatChart(...)

In [4]:
dashboard.save("../assets/json/final_dashboard.json")

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

In [5]:
#Load and Clean Census Population Data

df_pop = pd.read_csv("ACSDT5Y2023.B01003-Data.csv", skiprows=1)

# Rename all 5 columns
df_pop.columns = ["GEO_ID", "County", "Population", "Margin", "Extra"]

# Remove the first row that contains labels like "Geography"
df_pop = df_pop.iloc[1:]

# Keep only the useful columns
df_pop = df_pop[["County", "Population"]]

# Clean county names
df_pop["County"] = df_pop["County"].str.replace(" County, Iowa", "", regex=False)

# Convert population to number
df_pop["Population"] = pd.to_numeric(df_pop["Population"], errors="coerce")

# Drop missing rows
df_pop = df_pop.dropna()

df_pop.head()

      County  Population
1      Adams        3641
2  Allamakee       14038
3  Appanoose       12242
4    Audubon        5622
5     Benton       25698

In [6]:
# Rename column to match
df_pop = df_pop.rename(columns={"County": "County Name"})

#Merge Business and Population Data
#I rename the county column so both datasets use the same field name, then merge the population data with the business registration data.

df_merged = df_dashboard.merge(df_pop, on="County Name", how="left")

df_merged.head()

,Active or Inactive Business,Tax Type,Retail Permit Number,Consolidated Number,Name of Business,Address of the Business,State,County Name,Registration County Number,Business Location County Number,Department City Code,City Location of Business,Business Zip Code,NAICS code,Description of type of NAICS code,Date Permit was Issued,Date Permit was Cancelled,Issue Year,Population
0,Active,Retail Sales,308700211,308700111,"NOURISH MIND & BODY, LLC",1366 275TH ST,IA,Buchanan,10.0,10,2.0,JESUP,50648-9457,621399.0,Offices of All Other Miscellaneous Health Prac...,2023-05-01,NaN,2023,20645.0
1,Inactive,Retail Sales,177133565,NaN,"SIMMONS, RICHARD; TWO KAYAK WOODWORKING",509 SW ASH DR,IA,Polk,77.0,77,5.0,ANKENY,50023-2905,3219.0,Other Wood Product Manufacturing,2021-07-01,2024-06-01T00:00:00.000,2021,497441.0
2,Inactive,Retail Sales,633505392,NaN,NORTH FAYETTE COMMUNITY SCHOOL DIST,PO BOX 73 105 E MAIN ST,IA,Fayette,33.0,33,3.0,WEST UNION,52175-0073,7139.0,Other Amusement and Recreation Industries,2001-07-06,2021-11-11T00:00:00.000,2001,19393.0
3,Inactive,Retail Sales,168003811,NaN,"CHANCE, LINDA K; LINDAS QUILTING",1264 625TH AVE,IA,Monroe,68.0,68,3.0,LOVILIA,50150-8756,NaN,NaN,2008-07-01,2020-06-30T00:00:00.000,2008,7546.0
4,Active,Retail Sales,306903525,306903525,"OLSON, MARK A",1239 JAVELIN PL,IA,Boone,8.0,8,3.0,OGDEN,50212-7425,457110.0,Gasoline Stations with Convenience Stores,2025-05-16,NaN,2025,26669.0

In [7]:
# Group data by County
#I group the merged data by county to calculate the number of business records in each county and keep the population value for context.

df_county = df_merged.groupby("County Name").agg({
    "Population": "first",
    "Active or Inactive Business": "count"
}).reset_index()

df_county = df_county.rename(columns={
    "Active or Inactive Business": "Business Count"
})

df_county.head()

  County Name  Population  Business Count
0       Adair         NaN              24
1       Adams      3641.0              20
2   Allamakee     14038.0              56
3   Appanoose     12242.0              53
4     Audubon      5622.0              14

In [8]:
#top counties by business registrations

df_county_top = df_county.sort_values(

    by="Business Count",

    ascending=False

).head(15)

chart3 = alt.Chart(df_county_top).mark_bar().encode(

    x=alt.X("Business Count:Q", title="Number of Businesses"),

    y=alt.Y("County Name:N", sort="-x", title="County"),

    color=alt.Color(

        "Population:Q",

        title="Population",

        scale=alt.Scale(scheme="blues")

    ),

    tooltip=["County Name", "Business Count", "Population"]

).properties(

    title="Top 15 Counties by Business Registrations",

    width=600,

    height=400

)

chart3

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [9]:
# Context chart 2: top counties by population

df_population_top = df_pop.sort_values(by="Population", ascending=False).head(15)

chart4 = alt.Chart(df_population_top).mark_bar().encode(
    x=alt.X("Population:Q", title="Population"),
    y=alt.Y("County Name:N", sort="-x", title="County"),
    tooltip=["County Name", "Population"]
).properties(
    title="Top 15 Iowa Counties by Population",
    width=600,
    height=400
)

chart4

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)

alt.Chart(...)

In [10]:
# Save all visualization JSON files
dashboard.save("../assets/json/final_dashboard.json")
chart3.save("../assets/json/context_business_count.json")
chart4.save("../assets/json/context_population.json")

# Save cleaned population dataset with better name
df_pop.to_csv("iowa_county_population.csv", index=False)

/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)
/opt/anaconda3/lib/python3.12/site-packages/altair/utils/core.py:395: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  col = df[col_name].apply(to_list_if_array, convert_dtype=False)